### ISSUE TITLE
Error when building the docs

### ISSUE THREAD

**Issue by kottenator** [snide/sphinx_rtd_theme#247]
I'm installing self-hosted RTD now (commit: `e34541f3895`)

When I try to do `manage.py update_repos pip`

It raises an error:

```
Traceback (most recent call last):
  File "/var/www/readthedocs.org/readthedocs/projects/tasks.py", line 125, in run
    outcomes = self.build_docs()
  File "/var/www/readthedocs.org/readthedocs/projects/tasks.py", line 346, in build_docs
    outcomes['html'] = self.build_docs_html()
  File "/var/www/readthedocs.org/readthedocs/projects/tasks.py", line 362, in build_docs_html
    html_builder.append_conf()
  File "/var/www/readthedocs.org/readthedocs/doc_builder/backends/sphinx.py", line 78, in append_conf
    remote_version = self.version.get_vcs_slug()
AttributeError: 'Version' object has no attribute 'get_vcs_slug'
[15/Sep/2015 14:57:36] INFO [readthedocs.doc_builder.environments:274] (Build) [pip:latest] Build finished
```

**Comment by kottenator** [comment]
Oops! I'm sorry, wrong place, this bug belongs to rtfd/reathedocs
