### ISSUE TITLE
TypeError: unorderable types: str() > int()

### ISSUE THREAD

**Issue by Mingun** [snide/sphinx_rtd_theme#323]
Problem
=======

When I try build blender's documantation with latest version 1.10, I get `TypeError: unorderable types: str() > int()`:

```log
# Sphinx version: 1.4.6
# Python version: 3.4.4 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   manual/compositing/types/color/mix.rst:85: WARNING: inconsistent references in translated message
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  0%] about/contribute/build/index
# Loaded extensions:
#   alabaster (0.7.9) from d:\scripts\python\lib\site-packages\alabaster\__init__.py
#   vimeo (unknown version) from D:\Projects\other\blender_docs\exts\vimeo.py
#   sphinx.ext.mathjax (1.4.6) from d:\scripts\python\lib\site-packages\sphinx\ext\mathjax.py
#   youtube (unknown version) from D:\Projects\other\blender_docs\exts\youtube.py
Traceback (most recent call last):
  File "d:\scripts\python\lib\site-packages\sphinx\cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "d:\scripts\python\lib\site-packages\sphinx\application.py", line 297, in build
    self.builder.build_update()
  File "d:\scripts\python\lib\site-packages\sphinx\builders\__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "d:\scripts\python\lib\site-packages\sphinx\builders\__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "d:\scripts\python\lib\site-packages\sphinx\builders\__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "d:\scripts\python\lib\site-packages\sphinx\builders\__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "d:\scripts\python\lib\site-packages\sphinx\builders\html.py", line 452, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "d:\scripts\python\lib\site-packages\sphinx\builders\html.py", line 803, in handle_page
    output = self.templates.render(templatename, ctx)
  File "d:\scripts\python\lib\site-packages\sphinx\jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "d:\scripts\python\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\scripts\python\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\scripts\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "d:\scripts\python\lib\site-packages\sphinx\themes\basic\page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "D:\Projects\other\blender_docs\manual\../resources/templates\layout.html", line 1, in top-level template code
    {% extends "!layout.html" %}
  File "d:\scripts\python\lib\site-packages\sphinx_rtd_theme\layout.html", line 123, in top-level template code
    {% block menu %}
  File "d:\scripts\python\lib\site-packages\sphinx_rtd_theme\layout.html", line 124, in block "menu"
    {% set toctree = toctree(maxdepth=theme_navigation_depth, collapse=theme_collapse_navigation, includehidden=True) %}
  File "d:\scripts\python\lib\site-packages\jinja2\sandbox.py", line 355, in call
    return __context.call(__obj, *args, **kwargs)
  File "d:\scripts\python\lib\site-packages\sphinx\builders\html.py", line 793, in <lambda>
    ctx['toctree'] = lambda **kw: self._get_local_toctree(pagename, **kw)
  File "d:\scripts\python\lib\site-packages\sphinx\builders\html.py", line 729, in _get_local_toctree
    docname, self, collapse, **kwds))['fragment']
  File "d:\scripts\python\lib\site-packages\sphinx\environment.py", line 1234, in get_toctree_for
    prune=True, **kwds)
  File "d:\scripts\python\lib\site-packages\sphinx\environment.py", line 1508, in resolve_toctree
    self._toctree_prune(newnode, 1, prune and maxdepth or 0, collapse)
  File "d:\scripts\python\lib\site-packages\sphinx\environment.py", line 1302, in _toctree_prune
    if maxdepth > 0 and depth > maxdepth:
TypeError: unorderable types: str() > int()
```

Reason
======

Error occured in file `sphinx_rtd_theme\layout.html` at line 124:
```jinja
    {% set toctree = toctree(maxdepth=theme_navigation_depth, collapse=theme_collapse_navigation, includehidden=True) %}
```
After commit 923082974ce1aad26e8f12d6581c68b029b72d58 was added configuration setting `navigation_depth`, which used in that line. But underlying `ConfigParser` [do not implicitly convert datatypes](https://docs.python.org/3/library/configparser.html#supported-datatypes):

> Config parsers **do not guess datatypes of values in configuration files, always storing them internally as strings**. This means that if you need other datatypes, you should convert on your own:

Nevertheless, value of that setting run into template without conversion to `int`, and as result we would get `TypeError`, because `toctree()` function expects what `maxdepth` parameter would be `int`.

**Comment by Blendify** [comment]
This has been fixed in https://github.com/snide/sphinx_rtd_theme/commit/61eb48bc759ad428bde474dc6a441ed2a7adaf7f please close @ericholscher
